name: Build and Publish Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and tag Docker image
        run: |
          sudo docker build -t ghcr.io/orwent/1_image_vote:latest ./vote

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/orwent/1_image_vote:latest
