name: Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image from GHCR
        run: |
          docker pull ghcr.io/orwent/1_image_vote:latest

      - name: Stop and remove existing container
        run: |
          docker stop example-voting-app || true
          docker rm example-voting-app || true

      - name: Run new Docker container
        run: |
           docker compose up -d --name example-voting-app -p 80:80 ghcr.io/orwent/1_image_vote:latest
           
